# Generated by Django 2.2.10 on 2020-02-12 14:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('list', '0002_auto_20200212_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.RenameModel(
            old_name='List',
            new_name='Boardlist',
        ),
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=200, null=True)),
                ('image', models.FileField(null=True, upload_to='uploads/')),
                ('board', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='list.Board')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='list.Boardlist')),
            ],
        ),
    ]
