# Generated by Django 2.2.10 on 2020-02-13 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0003_auto_20200212_1456'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='user',
            new_name='owner',
        ),
        migrations.AddField(
            model_name='board',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='boardlist',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
