# Generated by Django 2.2.10 on 2020-02-17 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0005_auto_20200213_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='board',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='list.Boardlist'),
        ),
        migrations.AlterField(
            model_name='card',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='list.Board'),
        ),
    ]
