# Generated by Django 2.2.10 on 2020-02-17 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0006_auto_20200217_1521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='group',
        ),
    ]
