# Generated by Django 2.2.10 on 2020-02-18 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0007_remove_card_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='description',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
