# Generated by Django 2.2.10 on 2020-02-25 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0009_auto_20200225_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='position',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
