# Generated by Django 2.2.10 on 2020-02-26 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0012_auto_20200226_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
