# Generated by Django 2.2.10 on 2020-02-26 12:47

from django.db import migrations, models
import list.models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0013_auto_20200226_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='card_image_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=list.models.uploadto),
        ),
    ]
