# Generated by Django 2.2.10 on 2020-02-27 06:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('list', '0014_auto_20200226_2047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boardmember',
            name='user',
        ),
        migrations.AddField(
            model_name='boardmember',
            name='members',
            field=models.ForeignKey(blank='True', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
