# Generated by Django 2.2.10 on 2020-02-27 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0018_auto_20200227_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatart',
            field=models.FileField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
