# Generated by Django 2.2.10 on 2020-02-27 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0019_profile_avatart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='avatart',
            new_name='avatar',
        ),
    ]
