# Generated by Django 2.2.10 on 2020-02-27 10:37

from django.db import migrations, models
import list.models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0020_auto_20200227_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.FileField(blank=True, null=True, upload_to=list.models.avatar),
        ),
    ]
